print("this is my python code")
print("hello")
print("hello")
print("hello")
print("hello")
print("hello")

print("hello")
print("hello")
print("hello")
print("hello")
print("hello")

print("hello")
print("hello")